#!/bin/bash
# rm -rf var/cache/*
bin/console cache:clear --no-warmup
bin/console doctrine:database:drop --force
bin/console doctrine:database:create
bin/console doctrine:schema:create
bin/console doctrine:fixtures:load -n